default:
  image: docker:latest
  services:
    - docker:dind
    
stages:
    - build
    - test
    - deploy

variables:
  USERNAME: $CI_REGISTRY_USER
  PASSWORD: CI_REGISTRY_PASSWORD
  REGISTRY: CI_REGISTRY
  CONTAINER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build-dev:
  stage: build
  before_script:
    - echo "Wait for Docker daemon at tcp://localhost:2375"
    - while ! nc -z localhost 2375; do sleep 0.1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

    - echo $CONTAINER_IMAGE
  allow_failure: true
  only:
    - development

test-build:
  image: $CONTAINER_IMAGE
  before_script:
    - echo "Wait for Docker daemon at tcp://localhost:2375"
    - while ! nc -z localhost 2375; do sleep 0.1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - docker:dind
  script:
    - docker run -p 8000:8000 $CONTAINER_IMAGE
    - apk add curl
    - sleep 10
    - curl http://localhost:8000 && grep "The install worked successfully! Congratulations!"
  allow_failure: true
  when: manual
  only:
    - development


