default:
  image: docker:latest
  services:
    - docker:dind
    
stages:
    - build
    - test
    - deploy

variables:
  USERNAME: $CI_REGISTRY_USER
  PASSWORD: CI_REGISTRY_PASSWORD
  REGISTRY: CI_REGISTRY
  CONTAINER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"


build-dev:
  stage: build
  before_script:
    - echo "Wait for Docker daemon at tcp://localhost:2375"
    - while ! nc -z localhost 2375; do sleep 0.1; done
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

    - echo $CONTAINER_IMAGE
  allow_failure: true
  only:
    - development



test:
  stage: test
  image: $CONTAINER_IMAGE
  
  script:
  # adding of --settings=c2s.settings.test doesn't have impact now due to manage.py logic
  - echo "Running migration"
  - python manage.py migrate 
  - echo "Starting django test..."
  - python manage.py test 
  only:
  - development


