default:
  image: docker:latest
  services:
    - docker:dind
    
stages:
    - build
    - test
    - deploy


build-dev:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  #  - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
  #  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

    - echo $CI_REGISTRY:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

  #when: manual
  allow_failure: true
  only:
    - development

